//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankEntities : DbContext
    {
        public BankEntities()
            : base("name=BankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Operacii> Operacii { get; set; }
        public virtual DbSet<Prog> Prog { get; set; }
        public virtual DbSet<Schet> Schet { get; set; }
        public virtual DbSet<Sotrudnic> Sotrudnic { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Status_Scheta> Status_Scheta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
        public virtual DbSet<Tip_operacii> Tip_operacii { get; set; }
        public virtual DbSet<Valute> Valute { get; set; }
    }
}
