//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacii
    {
        public int ID { get; set; }
        public Nullable<decimal> Sum_In { get; set; }
        public Nullable<int> Out_FK { get; set; }
        public Nullable<int> In_FK { get; set; }
        public Nullable<int> Vneshcniy_Nscheta { get; set; }
        public Nullable<int> Tip_operazii_FK { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Sotrudnic_FK { get; set; }
        public int Status_FK { get; set; }
        public Nullable<decimal> Sum_Out { get; set; }
    
        public virtual Schet Schet { get; set; }
        public virtual Schet Schet1 { get; set; }
        public virtual Sotrudnic Sotrudnic { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tip_operacii Tip_operacii { get; set; }
    }
}
